version: '3.0'
services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=serverless
      - DEBUG=1
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=local
      - HOSTNAME="localstack"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      